### ISSUE TITLE
¿Sin RED tras Instalar? / No network after install? - Resolve it!!

### ISSUE THREAD

**Issue by DSkywalk** [rgb-x/system#10]
### Como recuperar la red, tras la instalación de RGBux *por @sirmagb00*

En primer lugar salir de Emulation Station, normalmente es el botón start del mando , o la tecla ENTER del teclado, debemos pulsar en “**Quit EmulationStation**”. Saldremos a un escritorio, donde en la esquina inferior izquierda, tenemos un botón de inicio, lo pulsamos y abrimos un emulador de terminal, donde tecleamos lo siguiente:

     sudo ifconfig –a

![image](https://user-images.githubusercontent.com/51505710/62415488-b0a51000-b62a-11e9-85af-a208f3a90c7e.png)
Observamos que nuestra tarjeta de red tiene el nombre de enp6s0, en tu caso cambiará será algo parecido.
a continuación tecleamos:

     sudo su -
     mc /etc/network

edita el fichero interfaces (pulsa **F4**)

![image](https://user-images.githubusercontent.com/51505710/62415499-e0541800-b62a-11e9-9d2b-feed84bd2617.png)

ves el segundo auto eth0?
descomenta esa linea y la de abajo
y cambia eth0 por "enp6s0" (cambia enp6s0 por el nombre de tu tarjeta de red)
debe quedar asi:
![imagen](https://user-images.githubusercontent.com/560310/62426576-c972fb80-b6e6-11e9-91dc-c26a8aeabaa4.png)

Ahora ,**F10** sal y guarda y reinicia ,a ver si ya lo tienes

      sudo reboot

si quieres reiniciar rapido

Recordar que RGB-uX tiene soporte de Samba, desde vuestro pc con windows o linux, podeis acceder a varias carpetas, para copiar juegos, o configurar diferentes archivos.

**Comment by sirmagb00** [comment]
**Como instalar emulador de PSP (ppsspp)**
En primer lugar abrimos un ventana de terminal y lanzamos el script de instalacion:
/opt/RGBux/installers/ppsspp.sh

Una vez terminada , llevará un rato, vamos a proceder a modificar el lanzador de psp, que no es correcto, se encuentra en la ruta /opt/RGBux/frontend/launchers
El archivo está nombrado como "lanzadorPSP.sh" lo editamos con mousepad, y lo dejamos asi:
#!/bin/bash

################################################################################
#                                                                              #
################################################################################

# Config video no necesaria se encarga 15khz-switchres-exec

# Genera la variable CORE y los CFGs
. /opt/RGBux/bin/launcher-ra-init


exec /opt/RGBux/bin/15khz-switchres-exec 720 480 60 /usr/games/PPSSPPQt --fullscreen --escape-exit "$@"

#Comandos para el inicio de ppsspp
#--state= // Set path to savestate which should be loaded
#--escape-exit  // Exits emulator instead of exiting to pause menu
#--pause-menu-exit // Similar to earlier one, but exits emulator from pause menu instead exiting just the game
#--fullscreen // Forces launch in fs

**Comment by DSkywalk** [comment]
fixed on RC5
